### ISSUE TITLE
Feature Request - Frame Width / Height

### ISSUE THREAD

**Issue by dsssssssss9** [DFRobot/pxt-DFRobot_HaskyLens#3]
Hi
Just got a HuskyLen & am very impressed

We mainly use MakeCode to teach STEM to children of various ages. 
The MakeCode extension for HuskyLens is good but we are wondering if there was a way to get the frame width & height , as i believe you can do in the Arduino library?
We are trying to make a robot car based on the MaQueen robot that tracks an oject . We have lef / right tracking done but  using frame  width & height we could determine if the object is moving away or towards the Robot so adjust forward / backward speed accordingly

Could this be added to the MakeCode extension please?

**Comment by tangjie133** [comment]
There seems to be one
